# This file serves as the default configuration, unless users override it.

[tool.basedpyright]
# typeCheckingMode = "standard"
# pythonVersion = "3.12" # TODO: keep in sync with python version
# 
# # Warn if function parameters lack type annotations
# reportMissingParameterType = "warning"
# 
# # Warn if generic types (e.g. List) are missing type args
# reportMissingTypeArgument = "warning"
# 
# # Warn when using members marked as private (e.g. _log)
# reportPrivateUsage = "warning"
# 
# # Warn when variable type can't be inferred or is 'Any'
# reportUnknownVariableType = "warning"
# 
# # Warn about declared but unused variables
# reportUnusedVariable = "warning"
# 
# exclude = [
#     "**/__pycache__",
#     "**/.*",
#     "**/bazel-*",
# ]
